### PR TITLE
Fix #15

### LINKED ISSUE #15: Allow user to login

### PR DESCRIPTION
**Pull request by kartikarora**
UI works for login and logout

Added fname and lname in PhotoProcess

### CODE REVIEW

**Comment by seanauriti** [comment]
Thank you!

**Comment by kartikarora** [comment]
:smile:

**Comment by seanauriti** [comment]
Login doesn't seem to work.  Also we'd like the app to open to the camera screen and allow for anonymous users to post like it did before.  Login will be on a drop down menu.

**Comment by kartikarora** [comment]
I'll add that asap. Have to go for classes right now! 

Sent from Yahoo Mail on Android 
 
  On Wed, 5 Oct, 2016 at 1:42 PM, Sean Auriti<notifications@github.com> wrote:   
Login doesn't seem to work. Also we'd like the app to open to the camera screen and allow for anonymous users to post like it did before. Login will be on a drop down menu.

**Comment by kartikarora** [comment]
@seanauriti I'm adding a login button at the top right corner of the camera button, that would be fine right?

**Pull request merged**
